export const log_detail = {
  db_all_log_project: "",
  db_all_log_menu: "",
  db_all_log_action: "",
  ip_address: "",
  user_name: "",
  branch_id: 1,
  database_id: 3,
  menu_id: null,
  commit: 1,
  //   db_all_log_project: "INVENTORY",
  //   db_all_log_menu: "Receivce",
  //   db_all_log_action: "SAVE",
  //   ip_address: "192.168.1.250",
  //   user_name: "2563003",
  //   branch_id: "1",
  //   database_id: "3",
  //   menu_id: "25",
  //   commit: "1",
};
