import numeral from "numeral";
export const receive_columns = [
  {
    title: "Receive No.",
    dataIndex: "receive_no",
    key: "receive_no",
    width: "10%",
    align: "left",
    sorter: {
      compare: (a, b) => a.receive_id - b.receive_id,
      multiple: 3,
    },
  },
  {
    title: "PO Ref.",
    dataIndex: "po_no",
    key: "po_no",
    width: "10%",
    align: "left",
    sorter: {
      compare: (a, b) => a.po_id - b.po_id,
      multiple: 3,
    },
  },
  {
    title: "Order Date",
    dataIndex: "receive_order_date",
    key: "receive_order_date",
    width: "7%",
    align: "center",
  },
  {
    title: "Receive Date",
    dataIndex: "tg_receive_date",
    key: "tg_receive_date",
    width: "7%",
    align: "center",
  },
  {
    title: "Vendor",
    dataIndex: "vendor_no_name",
    key: "vendor_no_name",
    width: "20%",
    align: "left",
    ellipsis: true,
  },
  {
    title: "Description",
    dataIndex: "receive_description",
    key: "receive_description",
    width: "15%",
    align: "left",
    ellipsis: true,
  },
  {
    title: "Receive By",
    dataIndex: "receive_created_by_no_name",
    key: "receive_created_by_no_name",
    width: "15%",
    align: "left",
    ellipsis: true,
  },
  {
    title: "Total Value",
    dataIndex: "tg_receive_total_amount",
    key: "tg_receive_total_amount",
    width: "10%",
    align: "right",
    sorter: {
      compare: (a, b) => a.tg_receive_total_amount - b.tg_receive_total_amount,
      multiple: 3,
    },
    render: (value) => numeral(value).format("0,0.000"),
  },

  {
    title: "Status",
    dataIndex: "trans_status_name",
    key: "trans_status_name",
    width: "8%",
    align: "left",
    sorter: {
      compare: (a, b) => a.tg_trans_status_id - b.tg_trans_status_id,
      multiple: 3,
    },
    ellipsis: true,
  },
];
export const recieve_detail_columns = [
  { id: 0, name: "Item", size: 5 },
  { id: 1, name: "Quantity", size: 3 },
  { id: 2, name: "Unit", size: 2 },
  { id: 3, name: "Quantity Done", size: 3 },
  { id: 4, name: "Unit Price", size: 3 },
  { id: 5, name: "Total Price", size: 3 },
  { id: 6, name: "Due Date", size: 3 },
];

export const qtyDoneColumns = [
  { id: 0, name: "Lot No.", size: 5 },
  { id: 1, name: "Receive Date", size: 4 },
  { id: 2, name: "MFG", size: 4 },
  { id: 3, name: "EXP", size: 4 },
  { id: 4, name: "Quantity", size: 3 },
  { id: 5, name: "Unit", size: 3 },
];
export const receive_fields = {
  receive_id: null,
  receive_no: null,
  receive_no_description: null,
  receive_order_date: null,
  receive_description: null,
  receive_agreement: null,
  receive_invoice_no: null,
  receive_invoice_date: null,
  receive_remark: null,
  receive_lock: 0,
  receive_actived: 1,
  receive_created: null,
  receive_created_by: null,
  receive_updated: null,
  receive_updated_by: null,
  po_id: null,
  po_no_description: null,
  branch_id: 1,
  branch_name: null,
  cost_center_id: null,
  payment_term_id: null,
  vendor_id: null,
  vat_id: 1,
  vat_rate: 0.07,
  currency_id: 1,
  currency_no: "THB",
  process_id: null,
  tg_receive_date: null,
  tg_receive_amount: 0,
  tg_receive_discount: 0,
  tg_receive_sum_amount: 0,
  tg_receive_vat_amount: 0,
  tg_receive_total_amount: 0,
  tg_trans_status_id: 1,
  tg_trans_close_id: null,
};

export const receive_detail_fields = {
  receive_id: null,
  item_id: null,
  uom_id: null,
  tg_receive_detail_id: null,
  tg_receive_detail_qty_remain: null,
  receive_detail_qty: null,
  receive_detail_price: null,
  receive_detail_discount: null,
  receive_detail_total_price: null,
  receive_detail_remark: null,
  receive_detail_receive_date: null,
};
