export const item_fields = {
  item_id: 0,
  item_no: null,
  item_name: "TEST",
  item_name_th: null,
  item_image_path: null,
  item_sale: 1,
  item_purchase: 1,
  item_price: 150,
  item_cost: 150,
  item_barcode: "TEST",
  item_weight: 0,
  item_mfd_leadtime: 0,
  item_min: 0,
  item_max: 0,
  item_customer_run_no: "SRL",
  uom_id: 1,
  uom_name: null,
  type_id: 1,
  type_name: null,
  category_id: 1,
  category_name: null,
  item_qty_tg: null,
  branch_id: 1,
  branch_name: null,
  identify_benefit_id: 1,
  identify_benefit_name: null,
  item_remark: null,
  item_actived: 1,
  item_created_by: null,
  item_updated_by: null,
  vat_id: 1,
  user_name: null,
  commit: 1,
  // item_id: 0,
  // item_no: null,
  // item_name: null,
  // item_name_th: null,
  // item_image_path: null,
  // item_sale: 0,
  // item_purchase: 0,
  // item_price: 0,
  // item_cost: 0,
  // item_barcode: null,
  // item_weight: 0,
  // item_mfd_leadtime: 0,
  // item_min: 0,
  // item_max: 0,
  // item_customer_run_no: "SRL",
  // uom_id: null,
  // type_id: null,
  // category_id: null,
  // item_qty_tg: null,
  // branch_id: 1,
  // identify_benefit_id: 1,
  // item_remark: null,
  // item_actived: 1,
  // item_created_by: null,
  // item_updated_by: null,
  // vat_id: 1,
  // user_name: "2563002",
  // commit: 1,
};

export const item_show_columns = [
  {
    title: "Code",
    dataIndex: "item_no",
  },
  {
    title: "Barcode",
    dataIndex: "item_barcode",
  },
  {
    title: "Item Name",
    dataIndex: "item_name",
  },
  {
    title: "Qty On Hand",
    dataIndex: "item_qty_tg",
  },
  {
    title: "Category",
    dataIndex: "category_id",
    ellipsis: true,
  },
  {
    title: "Description",
    dataIndex: "item_remark",
    ellipsis: true,
  },
];
