export const item_fields = {
  item_id: 0,
  item_no: null,
  item_name: null,
  item_name_th: null,
  item_image_path: null,
  item_sale: 0,
  item_purchase: 0,
  item_price: 0,
  item_cost: 0,
  item_barcode: null,
  item_weight: 0,
  item_mfd_leadtime: 0,
  item_min: 0,
  item_max: 0,
  item_customer_run_no: null,
  uom_id: null,
  type_id: null,
  category_id: null,
  item_qty_tg: null,
  branch_id: null,
  identify_benefit_id: null,
  item_remark: null,
  item_actived: 1,
  item_created_by: null,
  item_updated_by: null,
  vat_id: 1,
};
